export const ELEMENTS = {

    RELATORIO_GERAL_LABEL_TITLE: '.css-1c9l5hu',
    VOLTAR_BUTTON: '[data-testid="returnButton/home"]',
    ESTADO_FIELD_INPUT_FILTER: '[data-testid="modalEstadoInput"]',
    ESTADO_DROPDOWN_BUTTON: '[data-testid="modalEstadoInput"] > .MuiOutlinedInput-root > [data-testid="modalEstadoDropdownButton"] > [data-testid="ArrowDropDownIcon"]',
    MUNICIPIO_FIELD_INPUT_FILTER: '[data-testid="modalMunicipioInput"]',
    MUNICIPIO_DROPDOWN_BUTTON: '[data-testid="modalMunicipioDropdownButton"]',
    ESTABELECIMENTO_FIELD_INPUT_FILTER: '[data-testid="modalEstabelecimentoInput"]',
    ESTABELECIMENTO_DROPDOWN_BUTTON: '[data-testid="modalEstabelecimentoDropdownButton"]',
    INEEQUIPE_FIELD_INPUT_FILTER: '[data-testid="modalEquipeInput"]',
    INEEQUIPE_DROPDOWN_BUTTON: '[data-testid="modalEquipeDropdownButton"]',
    IDADE_INICIO_FIELD_INPUT_FILTER: '[data-testid="inputIdadeInicio"]',
    IDADE_FIM_FIELD_INPUT_FILTER: '[data-testid="inputIdadeFim"]',
    REALIZOU_ATENDIMENTO_FIELD_INPUT_FILTER: '[data-testid="inputRealizouAtendimento"]',
    REALIZOU_ATENDIMENTO_DROPDOWN_BUTTON: '[data-testid="ArrowDropDownIcon"]',
    METODO_COLETA_FIELD_INPUT_FILTER: '[data-testid="inputMetodoColeta"]',
    METODO_COLETA_DROPDOWN_BUTTON: '[data-testid="ArrowDropDownIcon"]',
    MOTIVO_EXAME_FIELD_INPUT_FILTER: '[data-testid="inputMotivoExame"]',
    MOTIVO_EXAME_DROPDOWN_BUTTON: '[data-testid="ArrowDropDownIcon"]',
    INSPECAO_COLO_FIELD_INPUT_FILTER: '[data-testid="inputInspecaoColo"]',
    INSPECAO_COLO_DROPDOWN_BUTTON: '[data-testid="ArrowDropDownIcon"]',
    PROFISSIONAL_RESPONSAVEL_DROPDOWN_BUTTON: '[data-testid="ArrowDropDownIcon"]',
    COLETA_DATA_RADIO_BUTTON: '[data-testid="optionFiltrarDataColeta"]',
    COLETA_PERIODO_RADIO_BUTTON: '[data-testid="optionFiltrarPeriodoColeta"]',
    CALENDARIO_DATA_COLETA_ICON: '[data-testid="CalendarIcon"]',
    RESULTADO_TESTE_HPV_DROPDOWN_BUTTON: '[data-testid="ArrowDropDownIcon"]',
    LABORATORIO_RESPONSAVEL_DROPDOWN_BUTTON: '[data-testid="modalEstadoDropdownButton"]',
    RESULTADO_DATA_RADIO_BUTTON: '[data-testid="optionFiltrarDataResultado"]',
    RESULTADO_PERIODO_RADIO_BUTTON: '[data-testid="optionFiltrarPeriodoResultado"]',
    CALENDARIO_DATA_INICIO_RESULTADO_ICON: '[data-testid="CalendarIcon"]',
    CALENDARIO_DATA_FIM_RESULTADO_ICON: '[data-testid="CalendarIcon"]',
    PESQUISAR_NOME_CPF_FIELD_INPUT_FILTER: '[data-testid="inputSearchByNameCpf"]',
    PESQUISAR_BUTTON: '[data-testid="SearchIcon"]',
    FILTRAR_SUBMIT_BUTTON: '[data-testid="submitFilterReportsHpv"]',
    LIMPAR_CLEAR_FILTER_BUTTON: '[data-testid="clearFilterReportsHpv"]',
    EXPORTAR_BUTTON: '[data-testid="exportButton"]',
    EXPORTAR_DROPDOWN_BUTTON: '[data-testid="exportButtonDropdown"]',
    MODAL_EXPORTAR_RELATORIO_DOWNLOAD: '[class="MuiTypography-root MuiTypography-h6 MuiDialogTitle-root css-ohyacs"]',
    DOWNLOAD_BUTTON: '[data-testid="FileDownloadIcon"]'


}